// deno-fmt-ignore-file
// deno-lint-ignore-file no-explicit-any ban-types ban-unused-ignore
//
// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// To generate this file: deno task start
//

/**
 * Array containing information about the Sales channel.
 */
export type SalesChannel = {
  /**
   * Sales channel identification.
   */
  id: string;
}[];
/**
 * Array containing payment rules information.
 */
export type GetRulesResponse = {
  /**
   * Rule identification.
   */
  id?: string;
  /**
   * Rule name.
   */
  name?: string;
  salesChannels?: SalesChannel;
  paymentSystem?: PaymentSystem;
  connector?: Connector;
  issuer?: Issuer;
  antifraud?: Antifraud;
  /**
   * Installment options information.
   */
  installmentOptions?: {
    /**
     * Indicates whether the billing date will be at the end (0) or beginning of the period (1).
     */
    dueDateType: 0 | 1;
    /**
     * Indicates the type of interest to calculate the value of the installments (Compound Interest = `null` or `0`, Simple Interest Rate with Tax = `1` and Single Interest = `2`).
     */
    interestRateMethod: null | 0 | 1 | 2;
    /**
     * Minimum value of each installment.
     */
    minimumInstallmentValue: number;
    /**
     * Array containing installments information.
     */
    installments: {
      /**
       * Rule identification.
       */
      ruleId: string;
      /**
       * Number of installments.
       */
      quantity: number;
      /**
       * Value of each installment.
       */
      value: number;
      /**
       * Interest rate (percent 0.1 = 10%).
       */
      interestRate: number;
      /**
       * Indicates the external installment system (if applicable).
       */
      isExternalInstallmentService: number;
      /**
       * Interest tax (percent 0.1 = 10%).
       */
      interestTax: number;
    }[];
  };
  /**
   * Indicates whether the payment is automatically authorized.
   */
  isSelfAuthorized?: boolean;
  /**
   * Indicates whether it is necessary to log in to make the payment.
   */
  requiresAuthentication?: boolean;
  /**
   * Indicates whether the rule is enabled in the store.
   */
  enabled?: boolean;
  /**
   * Indicates whether any specific type of installment service is used.
   */
  installmentsService?: boolean;
  /**
   * Indicates whether this rule should be considered the default for a given payment condition.
   */
  isDefault?: boolean;
  /**
   * Rule start date in [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html) format (`YYYY-MM-DDThh:mm:ss.fff`), if applicable.
   */
  beginDate?: string;
  /**
   * Rule end date in [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html) format (`YYYY-MM-DDThh:mm:ss.fff`), if applicable.
   */
  endDate?: string;
  /**
   * Commercial condition information.
   */
  condition?: {
    /**
     * Commercial condition identification.
     */
    id: string;
    /**
     * Indicates the minimum percentage of SKUs required in the cart using this commercial condition for it to be activated.
     */
    pullRate: number;
    /**
     * Commercial condition information.
     */
    name: string;
  };
  /**
   * Indicates the names of the accounts to which the rule is being applied exclusively.
   */
  multiMerchantList?: string[];
  /**
   * Information about rule application in a country.
   */
  country?: {
    /**
     * Country name.
     */
    name: string;
    /**
     * Country code (ISO 3166 alpha-2).
     */
    isoCode: string;
  };
  /**
   * Array containing information about the periods (days and hours) in which the rule is enabled.
   */
  dateIntervals?: {
    /**
     * Time, days of the week, and GMT time zone in which the rule is activated. This data is available in [CRON format](https://en.wikipedia.org/wiki/Cron).
     */
    start: string;
    /**
     * Time, days of the week and GMT time zone in which the rule is deactivated. This data is available in [CRON format](https://en.wikipedia.org/wiki/Cron).
     */
    end: string;
  }[];
  /**
   * Indicates whether interest can be calculated externally.
   */
  externalInterest?: boolean;
  /**
   * Minimum payment transaction amount for the rule to be applied.
   */
  minimumValue?: number;
  /**
   * Array containing information about the payment deadlines (applicable for credit payment method).
   */
  deadlines?: {
    /**
     * Array containing payment options information.
     */
    paymentOptions: {
      /**
       * Deadline in days to make payment.
       */
      days: number;
      /**
       * Interest rate applied (in percentage, e.g. `3.0` means 3%).
       */
      interestRate: number;
    }[];
  }[];
  /**
   * Information about the cobranded card.
   */
  cobrand?: {
    /**
     * Card name.
     */
    name: string;
  };
  /**
   * Information about the card category.
   */
  cardLevel?: {
    /**
     * Card category name (e.g. standard, gold, premium).
     */
    name: string;
  };
  /**
   * Range of card bins excluded from application of this rule.
   */
  excludedBinsRanges?: number;
}[];

export interface OpenAPI {
  /**
   * Returns the best installment options according to the parameters informed in the request.
   *
   * ## Permissions
   *
   * Any user or [application key](https://developers.vtex.com/docs/guides/api-authentication-using-application-keys) must have at least one of the appropriate [License Manager resources](https://help.vtex.com/en/tutorial/license-manager-resources--3q6ztrC8YynQf6rdc6euk3) to be able to successfully run this request. Otherwise they will receive a status code `403` error. These are the applicable resources for this endpoint:
   *
   * | **Product** | **Category** | **Resource** |
   * | --------------- | ----------------- | ----------------- |
   * | PCI Gateway | Payment-Make Payments | **View Payment Data** |
   *
   * There are no applicable [predefined roles](https://help.vtex.com/en/tutorial/predefined-roles--jGDurZKJHvHJS13LnO7Dy) for this resource list. You must [create a custom role](https://help.vtex.com/en/tutorial/roles--7HKK5Uau2H6wxE1rH5oRbc#creating-a-role) and add at least one of the resources above in order to use this endpoint. To learn more about machine authentication at VTEX, see [Authentication overview](https://developers.vtex.com/docs/guides/authentication).
   *
   * >❗ To prevent integrations from having excessive permissions, consider the [best practices for managing app keys](https://help.vtex.com/en/tutorial/best-practices-application-keys--7b6nD1VMHa49aI5brlOvJm) when assigning License Manager roles to integrations.
   */
  "GET /api/pvt/installments": {
    searchParams: {
      /**
       * Value to be divided into installments.
       */
      "request.value": number;
      /**
       * Sales channel identification. Attribute created by the seller in their VTEX store configuration.
       */
      "request.salesChannel"?: number;
      /**
       * Payment system identification.
       */
      "request.paymentDetails[0].id"?: number;
      /**
       * Total value paid in installments. If applied in the search, it must be equal to the `request.value` field.
       */
      "request.paymentDetails[0].value"?: number;
      /**
       * First six digits of the card number.
       */
      "request.paymentDetails[0].bin"?: number;
    };
    response: ValidRequest;
  };
  /**
   * Returns all affiliations (payment and anti-fraud providers) that are already configured in your store.
   *
   * ## Permissions
   *
   * Any user or [application key](https://developers.vtex.com/docs/guides/api-authentication-using-application-keys) must have at least one of the appropriate [License Manager resources](https://help.vtex.com/en/tutorial/license-manager-resources--3q6ztrC8YynQf6rdc6euk3) to be able to successfully run this request. Otherwise they will receive a status code `403` error. These are the applicable resources for this endpoint:
   *
   * | **Product** | **Category** | **Resource** |
   * | --------------- | ----------------- | ----------------- |
   * | PCI Gateway | Payment-Make Payments | **View Payment Data** |
   *
   * There are no applicable [predefined roles](https://help.vtex.com/en/tutorial/predefined-roles--jGDurZKJHvHJS13LnO7Dy) for this resource list. You must [create a custom role](https://help.vtex.com/en/tutorial/roles--7HKK5Uau2H6wxE1rH5oRbc#creating-a-role) and add at least one of the resources above in order to use this endpoint. To learn more about machine authentication at VTEX, see [Authentication overview](https://developers.vtex.com/docs/guides/authentication).
   *
   * >❗ To prevent integrations from having excessive permissions, consider the [best practices for managing app keys](https://help.vtex.com/en/tutorial/best-practices-application-keys--7b6nD1VMHa49aI5brlOvJm) when assigning License Manager roles to integrations.
   */
  "GET /api/pvt/affiliations": {
    response: {
      /**
       * Provider identification.
       */
      id?: string;
      /**
       * Provider implementation class name.
       */
      implementation?: string;
      /**
       * Provider name.
       */
      name?: string;
      /**
       * Array containing configuration information fields.
       */
      configuration?: {
        /**
         * Configuration parameter name.
         */
        name: string;
        /**
         * Configuration parameter value.
         */
        value: null | string;
        /**
         * Value key information.
         */
        valueKey: null | string;
      }[];
      /**
       * Indicates whether the provider is published and available for use.
       */
      isdelivered?: boolean;
      /**
       * Indicates whether the provider is configured.
       */
      isConfigured?: boolean;
    }[];
  };
  /**
   * Registers a new affiliation (payment or anti-fraud provider) in your store.
   *
   * ## Permissions
   *
   * Any user or [application key](https://developers.vtex.com/docs/guides/api-authentication-using-application-keys) must have at least one of the appropriate [License Manager resources](https://help.vtex.com/en/tutorial/license-manager-resources--3q6ztrC8YynQf6rdc6euk3) to be able to successfully run this request. Otherwise they will receive a status code `403` error. These are the applicable resources for this endpoint:
   *
   * | **Product** | **Category** | **Resource** |
   * | --------------- | ----------------- | ----------------- |
   * | PCI Gateway | Payment-ManageStore | **Manage Store** |
   *
   * There are no applicable [predefined roles](https://help.vtex.com/en/tutorial/predefined-roles--jGDurZKJHvHJS13LnO7Dy) for this resource list. You must [create a custom role](https://help.vtex.com/en/tutorial/roles--7HKK5Uau2H6wxE1rH5oRbc#creating-a-role) and add at least one of the resources above in order to use this endpoint. To learn more about machine authentication at VTEX, see [Authentication overview](https://developers.vtex.com/docs/guides/authentication).
   *
   * >❗ To prevent integrations from having excessive permissions, consider the [best practices for managing app keys](https://help.vtex.com/en/tutorial/best-practices-application-keys--7b6nD1VMHa49aI5brlOvJm) when assigning License Manager roles to integrations.
   */
  "POST /api/pvt/affiliations": {
    body: InsertAffiliationRequest;
    response: AffiliationResponse;
  };
  /**
   * Returns data for a specific affiliation (payment or anti-fraud provider).
   *
   * ## Permissions
   *
   * Any user or [application key](https://developers.vtex.com/docs/guides/api-authentication-using-application-keys) must have at least one of the appropriate [License Manager resources](https://help.vtex.com/en/tutorial/license-manager-resources--3q6ztrC8YynQf6rdc6euk3) to be able to successfully run this request. Otherwise they will receive a status code `403` error. These are the applicable resources for this endpoint:
   *
   * | **Product** | **Category** | **Resource** |
   * | --------------- | ----------------- | ----------------- |
   * | PCI Gateway | Payment-Make Payments | **View Payment Data** |
   *
   * There are no applicable [predefined roles](https://help.vtex.com/en/tutorial/predefined-roles--jGDurZKJHvHJS13LnO7Dy) for this resource list. You must [create a custom role](https://help.vtex.com/en/tutorial/roles--7HKK5Uau2H6wxE1rH5oRbc#creating-a-role) and add at least one of the resources above in order to use this endpoint. To learn more about machine authentication at VTEX, see [Authentication overview](https://developers.vtex.com/docs/guides/authentication).
   *
   * >❗ To prevent integrations from having excessive permissions, consider the [best practices for managing app keys](https://help.vtex.com/en/tutorial/best-practices-application-keys--7b6nD1VMHa49aI5brlOvJm) when assigning License Manager roles to integrations.
   */
  "GET /api/pvt/affiliations/:affiliationId": {
    response: AffiliationResponse;
  };
  /**
   * Updates information about an affiliation (payment or anti-fraud provider) configured in your store.
   *
   * ## Permissions
   *
   * Any user or [application key](https://developers.vtex.com/docs/guides/api-authentication-using-application-keys) must have at least one of the appropriate [License Manager resources](https://help.vtex.com/en/tutorial/license-manager-resources--3q6ztrC8YynQf6rdc6euk3) to be able to successfully run this request. Otherwise they will receive a status code `403` error. These are the applicable resources for this endpoint:
   *
   * | **Product** | **Category** | **Resource** |
   * | --------------- | ----------------- | ----------------- |
   * | PCI Gateway | Payment-ManageStore | **Manage Store** |
   *
   * There are no applicable [predefined roles](https://help.vtex.com/en/tutorial/predefined-roles--jGDurZKJHvHJS13LnO7Dy) for this resource list. You must [create a custom role](https://help.vtex.com/en/tutorial/roles--7HKK5Uau2H6wxE1rH5oRbc#creating-a-role) and add at least one of the resources above in order to use this endpoint. To learn more about machine authentication at VTEX, see [Authentication overview](https://developers.vtex.com/docs/guides/authentication).
   *
   * >❗ To prevent integrations from having excessive permissions, consider the [best practices for managing app keys](https://help.vtex.com/en/tutorial/best-practices-application-keys--7b6nD1VMHa49aI5brlOvJm) when assigning License Manager roles to integrations.
   */
  "PUT /api/pvt/affiliations/:affiliationId": {
    body: UpdateAffiliationRequest;
    response: AffiliationResponse;
  };
  /**
   * Returns all payment rules applied to the payment providers configured in your store.
   *
   * ## Permissions
   *
   * Any user or [application key](https://developers.vtex.com/docs/guides/api-authentication-using-application-keys) must have at least one of the appropriate [License Manager resources](https://help.vtex.com/en/tutorial/license-manager-resources--3q6ztrC8YynQf6rdc6euk3) to be able to successfully run this request. Otherwise they will receive a status code `403` error. These are the applicable resources for this endpoint:
   *
   * | **Product** | **Category** | **Resource** |
   * | --------------- | ----------------- | ----------------- |
   * | PCI Gateway | Payment-Make Payments | **View Payment Data** |
   *
   * There are no applicable [predefined roles](https://help.vtex.com/en/tutorial/predefined-roles--jGDurZKJHvHJS13LnO7Dy) for this resource list. You must [create a custom role](https://help.vtex.com/en/tutorial/roles--7HKK5Uau2H6wxE1rH5oRbc#creating-a-role) and add at least one of the resources above in order to use this endpoint. To learn more about machine authentication at VTEX, see [Authentication overview](https://developers.vtex.com/docs/guides/authentication).
   *
   * >❗ To prevent integrations from having excessive permissions, consider the [best practices for managing app keys](https://help.vtex.com/en/tutorial/best-practices-application-keys--7b6nD1VMHa49aI5brlOvJm) when assigning License Manager roles to integrations.
   */
  "GET /api/pvt/rules": {
    response: GetRulesResponse;
  };
  /**
   * Creates a new payment rule to be applied to the payment providers configured in your store.
   *
   * ## Permissions
   *
   * Any user or [application key](https://developers.vtex.com/docs/guides/api-authentication-using-application-keys) must have at least one of the appropriate [License Manager resources](https://help.vtex.com/en/tutorial/license-manager-resources--3q6ztrC8YynQf6rdc6euk3) to be able to successfully run this request. Otherwise they will receive a status code `403` error. These are the applicable resources for this endpoint:
   *
   * | **Product** | **Category** | **Resource** |
   * | --------------- | ----------------- | ----------------- |
   * | PCI Gateway | Payment-ManageStore | **Manage Store** |
   *
   * There are no applicable [predefined roles](https://help.vtex.com/en/tutorial/predefined-roles--jGDurZKJHvHJS13LnO7Dy) for this resource list. You must [create a custom role](https://help.vtex.com/en/tutorial/roles--7HKK5Uau2H6wxE1rH5oRbc#creating-a-role) and add at least one of the resources above in order to use this endpoint. To learn more about machine authentication at VTEX, see [Authentication overview](https://developers.vtex.com/docs/guides/authentication).
   *
   * >❗ To prevent integrations from having excessive permissions, consider the [best practices for managing app keys](https://help.vtex.com/en/tutorial/best-practices-application-keys--7b6nD1VMHa49aI5brlOvJm) when assigning License Manager roles to integrations.
   */
  "POST /api/pvt/rules": {
    body: InsertRuleRequest;
    response: RulesRequest;
  };
  /**
   * Returns data for a specific payment rule applied to the payment providers configured in your store.
   *
   * ## Permissions
   *
   * Any user or [application key](https://developers.vtex.com/docs/guides/api-authentication-using-application-keys) must have at least one of the appropriate [License Manager resources](https://help.vtex.com/en/tutorial/license-manager-resources--3q6ztrC8YynQf6rdc6euk3) to be able to successfully run this request. Otherwise they will receive a status code `403` error. These are the applicable resources for this endpoint:
   *
   * | **Product** | **Category** | **Resource** |
   * | --------------- | ----------------- | ----------------- |
   * | PCI Gateway | Payment-Make Payments | **View Payment Data** |
   *
   * There are no applicable [predefined roles](https://help.vtex.com/en/tutorial/predefined-roles--jGDurZKJHvHJS13LnO7Dy) for this resource list. You must [create a custom role](https://help.vtex.com/en/tutorial/roles--7HKK5Uau2H6wxE1rH5oRbc#creating-a-role) and add at least one of the resources above in order to use this endpoint. To learn more about machine authentication at VTEX, see [Authentication overview](https://developers.vtex.com/docs/guides/authentication).
   *
   * >❗ To prevent integrations from having excessive permissions, consider the [best practices for managing app keys](https://help.vtex.com/en/tutorial/best-practices-application-keys--7b6nD1VMHa49aI5brlOvJm) when assigning License Manager roles to integrations.
   */
  "GET /api/pvt/rules/:ruleId": {
    response: RulesRequest;
  };
  /**
   * Updates information about a specific payment rule applied to the payment providers configured in your store.
   *
   * ## Permissions
   *
   * Any user or [application key](https://developers.vtex.com/docs/guides/api-authentication-using-application-keys) must have at least one of the appropriate [License Manager resources](https://help.vtex.com/en/tutorial/license-manager-resources--3q6ztrC8YynQf6rdc6euk3) to be able to successfully run this request. Otherwise they will receive a status code `403` error. These are the applicable resources for this endpoint:
   *
   * | **Product** | **Category** | **Resource** |
   * | --------------- | ----------------- | ----------------- |
   * | PCI Gateway | Payment-ManageStore | **Manage Store** |
   *
   * There are no applicable [predefined roles](https://help.vtex.com/en/tutorial/predefined-roles--jGDurZKJHvHJS13LnO7Dy) for this resource list. You must [create a custom role](https://help.vtex.com/en/tutorial/roles--7HKK5Uau2H6wxE1rH5oRbc#creating-a-role) and add at least one of the resources above in order to use this endpoint. To learn more about machine authentication at VTEX, see [Authentication overview](https://developers.vtex.com/docs/guides/authentication).
   *
   * >❗ To prevent integrations from having excessive permissions, consider the [best practices for managing app keys](https://help.vtex.com/en/tutorial/best-practices-application-keys--7b6nD1VMHa49aI5brlOvJm) when assigning License Manager roles to integrations.
   */
  "PUT /api/pvt/rules/:ruleId": {
    body: RulesRequest;
    response: RulesRequest;
  };
  /**
   * Deletes a specific payment rule applied to the payment providers configured in your store.
   *
   * ## Permissions
   *
   * Any user or [application key](https://developers.vtex.com/docs/guides/api-authentication-using-application-keys) must have at least one of the appropriate [License Manager resources](https://help.vtex.com/en/tutorial/license-manager-resources--3q6ztrC8YynQf6rdc6euk3) to be able to successfully run this request. Otherwise they will receive a status code `403` error. These are the applicable resources for this endpoint:
   *
   * | **Product** | **Category** | **Resource** |
   * | --------------- | ----------------- | ----------------- |
   * | PCI Gateway | Payment-ManageStore | **Manage Store** |
   *
   * There are no applicable [predefined roles](https://help.vtex.com/en/tutorial/predefined-roles--jGDurZKJHvHJS13LnO7Dy) for this resource list. You must [create a custom role](https://help.vtex.com/en/tutorial/roles--7HKK5Uau2H6wxE1rH5oRbc#creating-a-role) and add at least one of the resources above in order to use this endpoint. To learn more about machine authentication at VTEX, see [Authentication overview](https://developers.vtex.com/docs/guides/authentication).
   *
   * >❗ To prevent integrations from having excessive permissions, consider the [best practices for managing app keys](https://help.vtex.com/en/tutorial/best-practices-application-keys--7b6nD1VMHa49aI5brlOvJm) when assigning License Manager roles to integrations.
   */
  "DELETE /api/pvt/rules/:ruleId": {};
  /**
   * Returns all payment methods (such as Visa, Master, among others) that can be used in your store.
   *
   * ## Permissions
   *
   * Any user or [application key](https://developers.vtex.com/docs/guides/api-authentication-using-application-keys) must have at least one of the appropriate [License Manager resources](https://help.vtex.com/en/tutorial/license-manager-resources--3q6ztrC8YynQf6rdc6euk3) to be able to successfully run this request. Otherwise they will receive a status code `403` error. These are the applicable resources for this endpoint:
   *
   * | **Product** | **Category** | **Resource** |
   * | --------------- | ----------------- | ----------------- |
   * | PCI Gateway | Payment-Make Payments | **View Payment Data** |
   *
   * There are no applicable [predefined roles](https://help.vtex.com/en/tutorial/predefined-roles--jGDurZKJHvHJS13LnO7Dy) for this resource list. You must [create a custom role](https://help.vtex.com/en/tutorial/roles--7HKK5Uau2H6wxE1rH5oRbc#creating-a-role) and add at least one of the resources above in order to use this endpoint. To learn more about machine authentication at VTEX, see [Authentication overview](https://developers.vtex.com/docs/guides/authentication).
   *
   * >❗ To prevent integrations from having excessive permissions, consider the [best practices for managing app keys](https://help.vtex.com/en/tutorial/best-practices-application-keys--7b6nD1VMHa49aI5brlOvJm) when assigning License Manager roles to integrations.
   */
  "GET /api/pvt/merchants/payment-systems": {
    searchParams: {
      /**
       * Sales channel ([trade policy](https://help.vtex.com/en/tutorial/how-trade-policies-work--6Xef8PZiFm40kg2STrMkMV)) identification. This parameter must be filled in if you wish to obtain information on payment methods available in a specific store sales channel.
       */
      salesChannel?: number;
    };
    /**
     * Payment methods information.
     */
    response: PaymentSystemsResponse[];
  };
  /**
   * This request is the first step to create a new transaction.
   *
   * ## Permissions
   *
   * Any user or [application key](https://developers.vtex.com/docs/guides/api-authentication-using-application-keys) must have at least one of the appropriate [License Manager resources](https://help.vtex.com/en/tutorial/license-manager-resources--3q6ztrC8YynQf6rdc6euk3) to be able to successfully run this request. Otherwise they will receive a status code `403` error. These are the applicable resources for this endpoint:
   *
   * | **Product** | **Category** | **Resource** |
   * | --------------- | ----------------- | ----------------- |
   * | PCI Gateway | Payment-Make Payments | **Process payments** |
   *
   * There are no applicable [predefined roles](https://help.vtex.com/en/tutorial/predefined-roles--jGDurZKJHvHJS13LnO7Dy) for this resource list. You must [create a custom role](https://help.vtex.com/en/tutorial/roles--7HKK5Uau2H6wxE1rH5oRbc#creating-a-role) and add at least one of the resources above in order to use this endpoint. To learn more about machine authentication at VTEX, see [Authentication overview](https://developers.vtex.com/docs/guides/authentication).
   *
   * >❗ To prevent integrations from having excessive permissions, consider the [best practices for managing app keys](https://help.vtex.com/en/tutorial/best-practices-application-keys--7b6nD1VMHa49aI5brlOvJm) when assigning License Manager roles to integrations.
   */
  "POST /api/pvt/transactions": {
    /**
     * New transaction request body information.
     */
    body: {
      /**
       * Transaction value. The value must be described without using separation for decimals, e.g. for a transaction with a value equal to 201.50, send 20150.
       */
      value: number;
      /**
       * Identification number that relates the transaction to a purchase order.
       */
      referenceId: string;
      /**
       * Store where the transaction was initiated.
       */
      channel: string;
      /**
       * [URN](https://en.wikipedia.org/wiki/Uniform_Resource_Name) information.
       */
      urn?: string;
      /**
       * Sales channel information.
       */
      salesChannel: string;
    };
    response: StartTransactionResponse;
  };
  /**
   * The second step to create a new transaction. This request is used to send the payment data through a public request.
   *
   * ## Permissions
   *
   * This endpoint does not require [authentication](https://developers.vtex.com/docs/guides/authentication) or [permissions](https://help.vtex.com/en/tutorial/license-manager-resources--3q6ztrC8YynQf6rdc6euk3).
   */
  "POST /api/pub/transactions/:transactionId/payments": {
    searchParams: {
      /**
       * Order identification.
       */
      orderId: string;
    };
    /**
     * Payment information.
     */
    body: {
      /**
       * Payment system identification.
       */
      paymentSystem: number;
      /**
       * Number of installments.
       */
      installments: number;
      /**
       * Currency code in ISO 4217 standard.
       */
      currencyCode: string;
      /**
       * Payment value.
       */
      value: number;
      /**
       * The interest rate.
       */
      installmentsInterestRate: number;
      /**
       * The value of each installment.
       */
      installmentsValue: number;
      /**
       * Value amount of the payment without interest applied. This value is the same as the `value` field when `installmentsInterestRate` is `0.0`.
       */
      referenceValue: number;
      fields: Fields;
      transaction: Transaction;
    }[];
  };
  /**
   * The second step to create a new transaction. This request is used to send the payment data through a private request.
   *
   * ## Permissions
   *
   * Any user or [application key](https://developers.vtex.com/docs/guides/api-authentication-using-application-keys) must have at least one of the appropriate [License Manager resources](https://help.vtex.com/en/tutorial/license-manager-resources--3q6ztrC8YynQf6rdc6euk3) to be able to successfully run this request. Otherwise they will receive a status code `403` error. These are the applicable resources for this endpoint:
   *
   * | **Product** | **Category** | **Resource** |
   * | --------------- | ----------------- | ----------------- |
   * | PCI Gateway | Payment-Make Payments | **Process payments** |
   *
   * There are no applicable [predefined roles](https://help.vtex.com/en/tutorial/predefined-roles--jGDurZKJHvHJS13LnO7Dy) for this resource list. You must [create a custom role](https://help.vtex.com/en/tutorial/roles--7HKK5Uau2H6wxE1rH5oRbc#creating-a-role) and add at least one of the resources above in order to use this endpoint. To learn more about machine authentication at VTEX, see [Authentication overview](https://developers.vtex.com/docs/guides/authentication).
   *
   * >❗ To prevent integrations from having excessive permissions, consider the [best practices for managing app keys](https://help.vtex.com/en/tutorial/best-practices-application-keys--7b6nD1VMHa49aI5brlOvJm) when assigning License Manager roles to integrations.
   */
  "POST /api/pvt/transactions/:transactionId/payments": {
    /**
     * Payment information.
     */
    body: {
      /**
       * Payment system identification.
       */
      paymentSystem: number;
      /**
       * Number of installments.
       */
      installments: number;
      /**
       * Currency code in ISO 4217 standard.
       */
      currencyCode: string;
      /**
       * Payment value.
       */
      value: number;
      /**
       * The interest rate.
       */
      installmentsInterestRate: number;
      /**
       * The value of each installment.
       */
      installmentsValue: number;
      /**
       * Value amount of the payment without interest applied. This value is the same as the `value` field when `installmentsInterestRate` is `0.0`.
       */
      referenceValue: number;
      fields: Fields3;
      transaction: Transaction;
    }[];
    response: PaymentDetailsResponse;
  };
  /**
   * The third step to create a new transaction. This request sends additional data related to the transaction, such as profile information, shopping cart, shipping data, among others.
   *
   * ## Permissions
   *
   * Any user or [application key](https://developers.vtex.com/docs/guides/api-authentication-using-application-keys) must have at least one of the appropriate [License Manager resources](https://help.vtex.com/en/tutorial/license-manager-resources--3q6ztrC8YynQf6rdc6euk3) to be able to successfully run this request. Otherwise they will receive a status code `403` error. These are the applicable resources for this endpoint:
   *
   * | **Product** | **Category** | **Resource** |
   * | --------------- | ----------------- | ----------------- |
   * | PCI Gateway | Payment-Make Payments | **Process payments** |
   *
   * There are no applicable [predefined roles](https://help.vtex.com/en/tutorial/predefined-roles--jGDurZKJHvHJS13LnO7Dy) for this resource list. You must [create a custom role](https://help.vtex.com/en/tutorial/roles--7HKK5Uau2H6wxE1rH5oRbc#creating-a-role) and add at least one of the resources above in order to use this endpoint. To learn more about machine authentication at VTEX, see [Authentication overview](https://developers.vtex.com/docs/guides/authentication).
   *
   * >❗ To prevent integrations from having excessive permissions, consider the [best practices for managing app keys](https://help.vtex.com/en/tutorial/best-practices-application-keys--7b6nD1VMHa49aI5brlOvJm) when assigning License Manager roles to integrations.
   */
  "POST /api/pvt/transactions/:transactionId/additional-data": {
    /**
     * Array containing additional data.
     */
    body: {
      /**
       * Dataset name. This information must be sent in escaped JSON format.
       */
      name: string;
      /**
       * Dataset values. This information must be sent in escaped JSON format.
       */
      value: string;
    }[];
  };
  /**
   * Use this request to update any information that has previously been sent on endpoint [3. Send additional data](https://developers.vtex.com/docs/api-reference/payments-gateway-api#post-/api/pvt/transactions/-transactionId-/additional-data).
   *
   * ## Permissions
   *
   * Any user or [application key](https://developers.vtex.com/docs/guides/api-authentication-using-application-keys) must have at least one of the appropriate [License Manager resources](https://help.vtex.com/en/tutorial/license-manager-resources--3q6ztrC8YynQf6rdc6euk3) to be able to successfully run this request. Otherwise they will receive a status code `403` error. These are the applicable resources for this endpoint:
   *
   * | **Product** | **Category** | **Resource** |
   * | --------------- | ----------------- | ----------------- |
   * | PCI Gateway | Payment-Make Payments | **Process payments** |
   *
   * There are no applicable [predefined roles](https://help.vtex.com/en/tutorial/predefined-roles--jGDurZKJHvHJS13LnO7Dy) for this resource list. You must [create a custom role](https://help.vtex.com/en/tutorial/roles--7HKK5Uau2H6wxE1rH5oRbc#creating-a-role) and add at least one of the resources above in order to use this endpoint. To learn more about machine authentication at VTEX, see [Authentication overview](https://developers.vtex.com/docs/guides/authentication).
   *
   * >❗ To prevent integrations from having excessive permissions, consider the [best practices for managing app keys](https://help.vtex.com/en/tutorial/best-practices-application-keys--7b6nD1VMHa49aI5brlOvJm) when assigning License Manager roles to integrations.
   */
  "PATCH /api/pvt/transactions/:transactionId/additional-data": {
    /**
     * Array containing additional data.
     */
    body: {
      /**
       * Dataset name. This information must be sent in escaped JSON format.
       */
      name: string;
      /**
       * Dataset values. This information must be sent in escaped JSON format.
       */
      value: string;
    }[];
  };
  /**
   * The fourth and last step to create a new transaction. It will authorized the new transaction creation according to the data previously informed in the latests requests.
   *
   * This step is the trigger to process each of payments that were received in step 2.
   *
   * Each payment will be sent to acquirer. If all payments are authorized, the transaction will be authorized. If one of the payments is denied, all payments in transaction will be cancelled.
   *
   * ## Permissions
   *
   * Any user or [application key](https://developers.vtex.com/docs/guides/api-authentication-using-application-keys) must have at least one of the appropriate [License Manager resources](https://help.vtex.com/en/tutorial/license-manager-resources--3q6ztrC8YynQf6rdc6euk3) to be able to successfully run this request. Otherwise they will receive a status code `403` error. These are the applicable resources for this endpoint:
   *
   * | **Product** | **Category** | **Resource** |
   * | --------------- | ----------------- | ----------------- |
   * | PCI Gateway | Payment-Make Payments | **Process payments** |
   *
   * There are no applicable [predefined roles](https://help.vtex.com/en/tutorial/predefined-roles--jGDurZKJHvHJS13LnO7Dy) for this resource list. You must [create a custom role](https://help.vtex.com/en/tutorial/roles--7HKK5Uau2H6wxE1rH5oRbc#creating-a-role) and add at least one of the resources above in order to use this endpoint. To learn more about machine authentication at VTEX, see [Authentication overview](https://developers.vtex.com/docs/guides/authentication).
   *
   * >❗ To prevent integrations from having excessive permissions, consider the [best practices for managing app keys](https://help.vtex.com/en/tutorial/best-practices-application-keys--7b6nD1VMHa49aI5brlOvJm) when assigning License Manager roles to integrations.
   */
  "POST /api/pvt/transactions/:transactionId/authorization-request": {
    /**
     * Authorize new transaction request body information.
     */
    body: {
      /**
       * Transaction identification.
       */
      transactionId: string;
      /**
       * Custom field for a transaction that can be displayed on the customer's invoice.
       */
      softDescriptor: string;
      /**
       * Indicates whether the transaction supports recurrence.
       */
      prepareForRecurrency: boolean;
    };
    response: SettleResponse;
  };
  /**
   * Returns data about a specific transaction made in your store.
   *
   * >⚠️ Do not use the `interactions.href` route which is part of this endpoint's response. This is an internal-only route not meant to be used by external developers.
   *
   * ## Permissions
   *
   * Any user or [application key](https://developers.vtex.com/docs/guides/api-authentication-using-application-keys) must have at least one of the appropriate [License Manager resources](https://help.vtex.com/en/tutorial/license-manager-resources--3q6ztrC8YynQf6rdc6euk3) to be able to successfully run this request. Otherwise they will receive a status code `403` error. These are the applicable resources for this endpoint:
   *
   * | **Product** | **Category** | **Resource** |
   * | --------------- | ----------------- | ----------------- |
   * | PCI Gateway | Payment-Make Payments | **View Payment Data** |
   *
   * There are no applicable [predefined roles](https://help.vtex.com/en/tutorial/predefined-roles--jGDurZKJHvHJS13LnO7Dy) for this resource list. You must [create a custom role](https://help.vtex.com/en/tutorial/roles--7HKK5Uau2H6wxE1rH5oRbc#creating-a-role) and add at least one of the resources above in order to use this endpoint. To learn more about machine authentication at VTEX, see [Authentication overview](https://developers.vtex.com/docs/guides/authentication).
   *
   * >❗ To prevent integrations from having excessive permissions, consider the [best practices for managing app keys](https://help.vtex.com/en/tutorial/best-practices-application-keys--7b6nD1VMHa49aI5brlOvJm) when assigning License Manager roles to integrations.
   */
  "GET /api/pvt/transactions/:transactionId": {
    response: TransactionDetailsResponse;
  };
  /**
   * Returns data about a specific payment made in your store.
   *
   * ## Permissions
   *
   * Any user or [application key](https://developers.vtex.com/docs/guides/api-authentication-using-application-keys) must have at least one of the appropriate [License Manager resources](https://help.vtex.com/en/tutorial/license-manager-resources--3q6ztrC8YynQf6rdc6euk3) to be able to successfully run this request. Otherwise they will receive a status code `403` error. These are the applicable resources for this endpoint:
   *
   * | **Product** | **Category** | **Resource** |
   * | --------------- | ----------------- | ----------------- |
   * | PCI Gateway | Payment-Make Payments | **View Payment Data** |
   *
   * There are no applicable [predefined roles](https://help.vtex.com/en/tutorial/predefined-roles--jGDurZKJHvHJS13LnO7Dy) for this resource list. You must [create a custom role](https://help.vtex.com/en/tutorial/roles--7HKK5Uau2H6wxE1rH5oRbc#creating-a-role) and add at least one of the resources above in order to use this endpoint. To learn more about machine authentication at VTEX, see [Authentication overview](https://developers.vtex.com/docs/guides/authentication).
   *
   * >❗ To prevent integrations from having excessive permissions, consider the [best practices for managing app keys](https://help.vtex.com/en/tutorial/best-practices-application-keys--7b6nD1VMHa49aI5brlOvJm) when assigning License Manager roles to integrations.
   */
  "GET /api/pvt/transactions/:transactionId/payments/:paymentId": {
    response: PaymentDetailsResponse;
  };
  /**
   * Returns settlement data associated with a specific transaction.
   *
   * ## Permissions
   *
   * Any user or [application key](https://developers.vtex.com/docs/guides/api-authentication-using-application-keys) must have at least one of the appropriate [License Manager resources](https://help.vtex.com/en/tutorial/license-manager-resources--3q6ztrC8YynQf6rdc6euk3) to be able to successfully run this request. Otherwise they will receive a status code `403` error. These are the applicable resources for this endpoint:
   *
   * | **Product** | **Category** | **Resource** |
   * | --------------- | ----------------- | ----------------- |
   * | PCI Gateway | Payment-Make Payments | **View Payment Data** |
   *
   * There are no applicable [predefined roles](https://help.vtex.com/en/tutorial/predefined-roles--jGDurZKJHvHJS13LnO7Dy) for this resource list. You must [create a custom role](https://help.vtex.com/en/tutorial/roles--7HKK5Uau2H6wxE1rH5oRbc#creating-a-role) and add at least one of the resources above in order to use this endpoint. To learn more about machine authentication at VTEX, see [Authentication overview](https://developers.vtex.com/docs/guides/authentication).
   *
   * >❗ To prevent integrations from having excessive permissions, consider the [best practices for managing app keys](https://help.vtex.com/en/tutorial/best-practices-application-keys--7b6nD1VMHa49aI5brlOvJm) when assigning License Manager roles to integrations.
   */
  "GET /api/pvt/transactions/:transactionId/settlements": {
    response: TransactionSettlementDetails;
  };
  /**
   * Settles the transaction amount. A payment settled means that the seller will receive the value of the purchase value after bank conciliation.
   *
   * >ℹ️ This call is mandatory to complete a transaction and its payments.
   *
   * ## Permissions
   *
   * Any user or [application key](https://developers.vtex.com/docs/guides/api-authentication-using-application-keys) must have at least one of the appropriate [License Manager resources](https://help.vtex.com/en/tutorial/license-manager-resources--3q6ztrC8YynQf6rdc6euk3) to be able to successfully run this request. Otherwise they will receive a status code `403` error. These are the applicable resources for this endpoint:
   *
   * | **Product** | **Category** | **Resource** |
   * | --------------- | ----------------- | ----------------- |
   * | PCI Gateway | Payment-Make Payments | **Process payments** |
   *
   * There are no applicable [predefined roles](https://help.vtex.com/en/tutorial/predefined-roles--jGDurZKJHvHJS13LnO7Dy) for this resource list. You must [create a custom role](https://help.vtex.com/en/tutorial/roles--7HKK5Uau2H6wxE1rH5oRbc#creating-a-role) and add at least one of the resources above in order to use this endpoint. To learn more about machine authentication at VTEX, see [Authentication overview](https://developers.vtex.com/docs/guides/authentication).
   *
   * >❗ To prevent integrations from having excessive permissions, consider the [best practices for managing app keys](https://help.vtex.com/en/tutorial/best-practices-application-keys--7b6nD1VMHa49aI5brlOvJm) when assigning License Manager roles to integrations.
   */
  "POST /api/pvt/transactions/:transactionId/settlement-request": {
    body: SettlethetransactionRequest;
    response: SettleResponse;
  };
  /**
   * Refunds the amount of the transaction that was previously settled.
   *
   * After a transaction is settled, this request can be used to partially or fully refund the transaction amount.
   *
   * Due to acquirer rules, it is not possible to perform this step online against the acquirer, and, if an error occurrs, we notify the seller company responsible by email to manually check the transaction status against the acquirer.
   *
   * ## Permissions
   *
   * Any user or [application key](https://developers.vtex.com/docs/guides/api-authentication-using-application-keys) must have at least one of the appropriate [License Manager resources](https://help.vtex.com/en/tutorial/license-manager-resources--3q6ztrC8YynQf6rdc6euk3) to be able to successfully run this request. Otherwise they will receive a status code `403` error. These are the applicable resources for this endpoint:
   *
   * | **Product** | **Category** | **Resource** |
   * | --------------- | ----------------- | ----------------- |
   * | PCI Gateway | Payment-Make Payments | **Process payments** |
   *
   * There are no applicable [predefined roles](https://help.vtex.com/en/tutorial/predefined-roles--jGDurZKJHvHJS13LnO7Dy) for this resource list. You must [create a custom role](https://help.vtex.com/en/tutorial/roles--7HKK5Uau2H6wxE1rH5oRbc#creating-a-role) and add at least one of the resources above in order to use this endpoint. To learn more about machine authentication at VTEX, see [Authentication overview](https://developers.vtex.com/docs/guides/authentication).
   *
   * >❗ To prevent integrations from having excessive permissions, consider the [best practices for managing app keys](https://help.vtex.com/en/tutorial/best-practices-application-keys--7b6nD1VMHa49aI5brlOvJm) when assigning License Manager roles to integrations.
   */
  "POST /api/pvt/transactions/:transactionId/refunding-request": {
    body: RefundthetransactionRequest;
    response: SettleResponse;
  };
  /**
   * Cancels a transaction that was previously approved, but not settled. It is possible to cancel partially or complete value of the transaction.
   *
   * Due to acquirer rules it is not possible to perform this step online against the acquirer.
   *
   * ## Permissions
   *
   * Any user or [application key](https://developers.vtex.com/docs/guides/api-authentication-using-application-keys) must have at least one of the appropriate [License Manager resources](https://help.vtex.com/en/tutorial/license-manager-resources--3q6ztrC8YynQf6rdc6euk3) to be able to successfully run this request. Otherwise they will receive a status code `403` error. These are the applicable resources for this endpoint:
   *
   * | **Product** | **Category** | **Resource** |
   * | --------------- | ----------------- | ----------------- |
   * | PCI Gateway | Payment-Make Payments | **Process payments** |
   *
   * There are no applicable [predefined roles](https://help.vtex.com/en/tutorial/predefined-roles--jGDurZKJHvHJS13LnO7Dy) for this resource list. You must [create a custom role](https://help.vtex.com/en/tutorial/roles--7HKK5Uau2H6wxE1rH5oRbc#creating-a-role) and add at least one of the resources above in order to use this endpoint. To learn more about machine authentication at VTEX, see [Authentication overview](https://developers.vtex.com/docs/guides/authentication).
   *
   * >❗ To prevent integrations from having excessive permissions, consider the [best practices for managing app keys](https://help.vtex.com/en/tutorial/best-practices-application-keys--7b6nD1VMHa49aI5brlOvJm) when assigning License Manager roles to integrations.
   */
  "POST /api/pvt/transactions/:transactionId/cancellation-request": {
    body: CancelthetransactionRequest;
    response: SettleResponse;
  };
}
/**
 * Installments options response body information.
 */
export interface ValidRequest {
  /**
   * Value to be paid in installments.
   */
  value: number;
  /**
   * Installments information.
   */
  installments: Installment[];
}
/**
 * Installment options information.
 */
export interface Installment {
  payment: Payment;
  /**
   * Array containing information about installment options.
   */
  options: Option[];
}
/**
 * Payment system information.
 */
export interface Payment {
  /**
   * Payment system identification.
   */
  id: number;
  /**
   * Payment system name.
   */
  name: string;
  /**
   * First six digits of the card number.
   */
  bin: string;
  /**
   * Value to be paid in installments.
   */
  value: number;
  /**
   * Indicates whether the payment system is automatically applied by default.
   */
  isDefault: boolean;
  self: Self;
}
/**
 * Object containing the payment system reference route.
 */
export interface Self {
  /**
   * Payment system reference route.
   */
  href: string;
}
/**
 * Installment options information.
 */
export interface Option {
  /**
   * Rule identification.
   */
  ruleId: string;
  /**
   * Number of installments.
   */
  quantity: number;
  /**
   * Value of each installment.
   */
  value: number;
  /**
   * Interest rate (percent 0.1 = 10%).
   */
  interestRate: number;
  /**
   * Indicates the external installment system (if applicable).
   */
  isExternalInstallmentService: number;
  /**
   * Interest tax (percent 0.1 = 10%).
   */
  interestTax: number;
}
/**
 * Insert new affiliation request body information.
 */
export interface InsertAffiliationRequest {
  /**
   * Provider implementation class name.
   */
  implementation: string;
  /**
   * Provider name.
   */
  name: string;
  /**
   * Array containing provider configuration information.
   */
  configuration: {
    /**
     * Configuration parameter name.
     */
    name: string;
    /**
     * Configuration parameter value.
     */
    value: string;
  }[];
  /**
   * Indicates whether the provider is published and available for use.
   */
  isdelivered: boolean;
  /**
   * Indicates whether the provider is configured.
   */
  isConfigured: boolean;
}
/**
 * Affiliation by ID response body information.
 */
export interface AffiliationResponse {
  /**
   * Provider identification.
   */
  id: string;
  /**
   * Provider implementation class name.
   */
  implementation: string;
  /**
   * Provider name.
   */
  name: string;
  /**
   * Array containing provider configuration information.
   */
  configuration: {
    /**
     * Configuration parameter name.
     */
    name: string;
    /**
     * Configuration parameter value.
     */
    value: string;
    /**
     * Value key information.
     */
    valueKey: string;
  }[];
  /**
   * Indicates whether the provider is published and available for use.
   */
  isdelivered: boolean;
  /**
   * Indicates whether the provider is configured.
   */
  isConfigured: boolean;
}
/**
 * Update affiliation by ID request body information.
 */
export interface UpdateAffiliationRequest {
  /**
   * Provider identification.
   */
  id: string;
  /**
   * Provider implementation class name.
   */
  implementation: string;
  /**
   * Provider name.
   */
  name: string;
  /**
   * Array containing provider configuration information.
   */
  configuration: {
    /**
     * Configuration parameter name.
     */
    name: string;
    /**
     * Configuration parameter value.
     */
    value: string;
    /**
     * Value key information.
     */
    valueKey: string;
  }[];
  /**
   * Indicates whether the provider is published and available for use.
   */
  isdelivered: boolean;
  /**
   * Indicates whether the provider is configured.
   */
  isConfigured: boolean;
}
/**
 * Payment system information.
 */
export interface PaymentSystem {
  /**
   * Payment system identification.
   */
  id: number;
  /**
   * Payment system name.
   */
  name: string;
  /**
   * Payment system implementation class name.
   */
  implementation: string;
}
/**
 * Connector (payment provider) information.
 */
export interface Connector {
  /**
   * Connector (payment provider) implementation class name.
   */
  implementation: string;
  /**
   * Affiliation connector (payment provider) identification.
   */
  affiliationId: string;
}
/**
 * Card issuer information.
 */
export interface Issuer {
  /**
   * Card issuer name.
   */
  name: string;
}
/**
 * Anti-fraud information.
 */
export interface Antifraud {
  /**
   * Connector (anti-fraud provider) implementation class name.
   */
  implementation: string;
  /**
   * Affiliation connector (anti-fraud provider) identification.
   */
  affiliationId: string;
}
/**
 * New payment rule request body information.
 */
export interface InsertRuleRequest {
  /**
   * Rule name.
   */
  name: string;
  salesChannels: SalesChannel;
  paymentSystem: PaymentSystem;
  connector: Connector;
  issuer: Issuer;
  antifraud: Antifraud;
  /**
   * Installment options information.
   */
  installmentOptions: {
    /**
     * Indicates whether the billing date will be at the end (0) or beginning of the period (1).
     */
    dueDateType: 0 | 1;
    /**
     * Indicates the type of interest to calculate the value of the installments (Compound Interest = `null` or `0`, Simple Interest Rate with Tax = `1` and Single Interest = `2`).
     */
    interestRateMethod: null | 0 | 1 | 2;
    /**
     * Minimum value of each installment.
     */
    minimumInstallmentValue: number;
    /**
     * Array containing installments information.
     */
    installments: {
      /**
       * Rule identification.
       */
      ruleId: string;
      /**
       * Number of installments.
       */
      quantity: number;
      /**
       * Value of each installment.
       */
      value: number;
      /**
       * Interest rate (percent 0.1 = 10%).
       */
      interestRate: number;
      /**
       * Indicates the external installment system (if applicable).
       */
      isExternalInstallmentService: number;
      /**
       * Interest tax (percent 0.1 = 10%).
       */
      interestTax: number;
    }[];
  };
  /**
   * Indicates whether the payment is automatically authorized.
   */
  isSelfAuthorized: boolean;
  /**
   * Indicates whether it is necessary to log in to make the payment.
   */
  requiresAuthentication: boolean;
  /**
   * Indicates whether the rule is enabled in the store.
   */
  enabled: boolean;
  /**
   * Indicates whether any specific type of installment service is used.
   */
  installmentsService: boolean;
  /**
   * Indicates whether this rule should be considered the default for a given payment condition.
   */
  isDefault: boolean;
  /**
   * Rule start date in [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html) format (`YYYY-MM-DDThh:mm:ss.fff`), if applicable.
   */
  beginDate: string;
  /**
   * Rule end date in [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html) format (`YYYY-MM-DDThh:mm:ss.fff`), if applicable.
   */
  endDate: string;
  /**
   * Commercial condition information.
   */
  condition: {
    /**
     * Commercial condition identification.
     */
    id: string;
    /**
     * Indicates the minimum percentage of SKUs required in the cart using this commercial condition for it to be activated.
     */
    pullRate: number;
    /**
     * Commercial condition information.
     */
    name: string;
  };
  /**
   * Indicates the names of the accounts to which the rule is being applied exclusively.
   */
  multiMerchantList: string[];
  /**
   * Information about rule application in a country.
   */
  country: {
    /**
     * Country name.
     */
    name: string;
    /**
     * Country code (ISO 3166 alpha-2).
     */
    isoCode: string;
  };
  /**
   * Array containing information about the periods (days and hours) in which the rule is enabled.
   */
  dateIntervals: {
    /**
     * Time, days of the week, and GMT time zone in which the rule is activated. This data is available in [CRON format](https://en.wikipedia.org/wiki/Cron).
     */
    start: string;
    /**
     * Time, days of the week and GMT time zone in which the rule is deactivated. This data is available in [CRON format](https://en.wikipedia.org/wiki/Cron).
     */
    end: string;
  }[];
  /**
   * Indicates whether interest can be calculated externally.
   */
  externalInterest?: boolean;
  /**
   * Minimum payment transaction amount for the rule to be applied.
   */
  minimumValue?: number;
  /**
   * Array containing information about the payment deadlines (applicable for credit payment method).
   */
  deadlines?: {
    /**
     * Array containing payment options information.
     */
    paymentOptions: {
      /**
       * Deadline in days to make payment.
       */
      days: number;
      /**
       * Interest rate applied (in percentage, e.g. `3.0` means 3%).
       */
      interestRate: number;
    }[];
  }[];
  /**
   * Information about the cobranded card.
   */
  cobrand?: {
    /**
     * Card name.
     */
    name: string;
  };
  /**
   * Information about the card category.
   */
  cardLevel?: {
    /**
     * Card category name (e.g. standard, gold, premium).
     */
    name: string;
  };
  /**
   * Range of card bins excluded from application of this rule.
   */
  excludedBinsRanges?: number;
}
/**
 * Payment rules information.
 */
export interface RulesRequest {
  /**
   * Rule identification.
   */
  id: string;
  /**
   * Rule name.
   */
  name: string;
  salesChannels: SalesChannel;
  paymentSystem: PaymentSystem;
  connector: Connector;
  issuer: Issuer;
  antifraud: Antifraud;
  /**
   * Installment options information.
   */
  installmentOptions: {
    /**
     * Indicates whether the billing date will be at the end (0) or beginning of the period (1).
     */
    dueDateType: 0 | 1;
    /**
     * Indicates the type of interest to calculate the value of the installments (Compound Interest = `null` or `0`, Simple Interest Rate with Tax = `1` and Single Interest = `2`).
     */
    interestRateMethod: null | 0 | 1 | 2;
    /**
     * Minimum value of each installment.
     */
    minimumInstallmentValue: number;
    /**
     * Array containing installments information.
     */
    installments: {
      /**
       * Rule identification.
       */
      ruleId: string;
      /**
       * Number of installments.
       */
      quantity: number;
      /**
       * Value of each installment.
       */
      value: number;
      /**
       * Interest rate (percent 0.1 = 10%).
       */
      interestRate: number;
      /**
       * Indicates the external installment system (if applicable).
       */
      isExternalInstallmentService: number;
      /**
       * Interest tax (percent 0.1 = 10%).
       */
      interestTax: number;
    }[];
  };
  /**
   * Indicates whether the payment is automatically authorized.
   */
  isSelfAuthorized: boolean;
  /**
   * Indicates whether it is necessary to log in to make the payment.
   */
  requiresAuthentication: boolean;
  /**
   * Indicates whether the rule is enabled in the store.
   */
  enabled: boolean;
  /**
   * Indicates whether any specific type of installment service is used.
   */
  installmentsService: boolean;
  /**
   * Indicates whether this rule should be considered the default for a given payment condition.
   */
  isDefault: boolean;
  /**
   * Rule start date in [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html) format (`YYYY-MM-DDThh:mm:ss.fff`), if applicable.
   */
  beginDate: string;
  /**
   * Rule end date in [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html) format (`YYYY-MM-DDThh:mm:ss.fff`), if applicable.
   */
  endDate: string;
  /**
   * Commercial condition information.
   */
  condition: {
    /**
     * Commercial condition identification.
     */
    id: string;
    /**
     * Indicates the minimum percentage of SKUs required in the cart using this commercial condition for it to be activated.
     */
    pullRate: number;
    /**
     * Commercial condition information.
     */
    name: string;
  };
  /**
   * Indicates the names of the accounts to which the rule is being applied exclusively.
   */
  multiMerchantList: string[];
  /**
   * Information about rule application in a country.
   */
  country: {
    /**
     * Country name.
     */
    name: string;
    /**
     * Country code (ISO 3166 alpha-2).
     */
    isoCode: string;
  };
  /**
   * Array containing information about the periods (days and hours) in which the rule is enabled.
   */
  dateIntervals: {
    /**
     * Time, days of the week, and GMT time zone in which the rule is activated. This data is available in [CRON format](https://en.wikipedia.org/wiki/Cron).
     */
    start: string;
    /**
     * Time, days of the week and GMT time zone in which the rule is deactivated. This data is available in [CRON format](https://en.wikipedia.org/wiki/Cron).
     */
    end: string;
  }[];
  /**
   * Indicates whether interest can be calculated externally.
   */
  externalInterest?: boolean;
  /**
   * Minimum payment transaction amount for the rule to be applied.
   */
  minimumValue?: number;
  /**
   * Array containing information about the payment deadlines (applicable for credit payment method).
   */
  deadlines?: {
    /**
     * Array containing payment options information.
     */
    paymentOptions: {
      /**
       * Deadline in days to make payment.
       */
      days: number;
      /**
       * Interest rate applied (in percentage, e.g. `3.0` means 3%).
       */
      interestRate: number;
    }[];
  }[];
  /**
   * Information about the cobranded card.
   */
  cobrand?: {
    /**
     * Card name.
     */
    name: string;
  };
  /**
   * Information about the card category.
   */
  cardLevel?: {
    /**
     * Card category name (e.g. standard, gold, premium).
     */
    name: string;
  };
  /**
   * Range of card bins excluded from application of this rule.
   */
  excludedBinsRanges?: number;
}
/**
 * Available payment methods response body information.
 */
export interface PaymentSystemsResponse {
  /**
   * Payment method identification.
   */
  id: number;
  /**
   * Payment method name.
   */
  name: string;
  /**
   * Indicates whether a document is required.
   */
  requiresDocument: boolean;
  /**
   * Payment method implementation class name.
   */
  implementation: string;
  /**
   * Connector (payment provider) implementation class name.
   */
  connectorImplementation: string;
  /**
   * Connector (anti-fraud provider) implementation class name.
   */
  antifraudConnectorImplementation: string;
  /**
   * Payment group name.
   */
  groupName: string;
  /**
   * Indicates whether the payment method allows redirection.
   */
  redirect: boolean;
  /**
   * Indicates whether it is custom.
   */
  isCustom: boolean;
  /**
   * Indicates whether the payment is automatically authorized.
   */
  isSelfAuthorized: boolean;
  /**
   * Indicates whether it is necessary to log in to make the payment.
   */
  requiresAuthentication: boolean;
  /**
   * Indicates whether the payment method allows installments.
   */
  allowInstallments: boolean;
  /**
   * Indicates whether it is possible to restrict the use of specific BIN codes (only applicable for cards).
   */
  allowBinExclusion: boolean;
  /**
   * Indicates whether the method allows multiple payments. Example of `false`: debit card.
   */
  allowMultiple: boolean;
  /**
   * Indicates whether it is possible to identify the name of the bank responsible for issuing the card.
   */
  allowIssuer: boolean;
  /**
   * Indicates whether it is possible to restrict a payment rule by the country where the purchase is made.
   */
  allowCountry: boolean;
  /**
   * Indicates whether to restrict a payment rule by commercial policy type.
   */
  allowCommercialPolicy: boolean;
  /**
   * Indicates whether to restrict a payment rule by commercial condition type.
   */
  allowCommercialCondition: boolean;
  /**
   * Indicates whether it is possible to restrict a period for making the payment.
   */
  allowPeriod: boolean;
  /**
   * Indicates whether the payment method is available for use.
   */
  isAvailable: boolean;
  /**
   * Description of the payment method.
   */
  description: string;
  /**
   * Indicates whether the payment method supports recurrence.
   */
  supportRecurrence: boolean;
  validator: Validator;
  /**
   * App dependencies information.
   */
  appDependencies: string;
  /**
   * Indicates whether a document is shown.
   */
  displayDocument: boolean;
  /**
   * Payment due date.
   */
  dueDate: string;
  /**
   * Indicates the possibility of payment notification (used by bank invoices and notes payable).
   */
  allowNotification: boolean;
  /**
   * Affiliation connector (payment provider) identification.
   */
  affiliationId: string;
  /**
   * Information about payment availability.
   */
  availablePayments: string;
  /**
   * Amount of time (in minutes) until the payment date (`dueDate`).
   */
  dueDateMinutes: number;
}
/**
 * Validator information.
 */
export interface Validator {
  /**
   * [Regex](https://regexr.com/) information.
   */
  regex: string;
  /**
   * Validator mask.
   */
  mask: string;
  /**
   * Card code regular mask.
   */
  cardCodeMask: string;
  /**
   * Card code regular expression.
   */
  cardCodeRegex: string;
  /**
   * Array containing weigths information.
   */
  weights: number[];
  /**
   * Indicates whether it is necessary to use the CVV code to complete a transaction with payment made by card.
   */
  useCvv: boolean;
  /**
   * Indicates whether it is necessary to use the expiration date to complete a card payment transaction.
   */
  useExpirationDate: boolean;
  /**
   * Indicates whether it is necessary to use the card holder name to complete a payment transaction made by card.
   */
  useCardHolderName: boolean;
  /**
   * Indicates whether it is necessary to use the billing address to complete a card payment transaction.
   */
  useBillingAddress: boolean;
  /**
   * Information about valid card lengths.
   */
  validCardLengths: string;
}
/**
 * New transaction response body information.
 */
export interface StartTransactionResponse {
  /**
   * Transaction identification.
   */
  id: string;
  /**
   * Transaction identification (same value of the `id` field).
   */
  transactionId: string;
  /**
   * Identification number that relates the transaction to a purchase order. It can be also used for anti-fraud to identify the transaction.
   */
  referenceKey: string;
  interactions: Interactions;
  settlements: Settlements;
  payments: Payments;
  refunds: Refunds;
  cancellations: Cancellations;
  capabilities: Capabilities;
  /**
   * Field that represents the possible transaction timeout statuses. Possible statuses and meanings: `0` = NotStarted, `1` = CancellingOrFinishing, `2` = CancellingOrFinishingByTimeout, `3` = CancelledOrFinished and `4` = TriesExceeded.
   */
  timeoutStatus: 0 | 1 | 2 | 3 | 4;
  /**
   * Total refunded transaction amount.
   */
  totalRefunds: number;
  /**
   * Transaction status.
   */
  status: string;
  /**
   * Transaction value.
   */
  value: number;
  /**
   * Receiver [URI](https://en.wikipedia.org/wiki/Uniform_Resource_Identifier) information.
   */
  receiverUri: string;
  /**
   * Transaction start date.
   */
  startDate: string;
  /**
   * Transaction authorization token.
   */
  authorizationToken: string;
  /**
   * Transaction authorization date.
   */
  authorizationDate: string;
  /**
   * Transaction completion token.
   */
  commitmentToken: string;
  /**
   * Transaction completion date.
   */
  commitmentDate: string;
  /**
   * Transaction refund token.
   */
  refundingToken: string;
  /**
   * Transaction refund date.
   */
  refundingDate: string;
  /**
   * Transaction cancellation token.
   */
  cancelationToken: string;
  /**
   * Transaction cancellation date.
   */
  cancelationDate: string;
  /**
   * Field containing transaction information.
   */
  fields: Field[];
  /**
   * IP address information.
   */
  ipAddress: string;
  /**
   * Session identification.
   */
  sessionId: string;
  /**
   * Random [UUID](https://en.wikipedia.org/wiki/Universally_unique_identifier) V4 generated when the Request Capture receives a session that does not contain the macID already set. This value is set to the cookie `VtexRCMacIdv7`. The cookie has 1 year of expiration.
   */
  macId: string;
  /**
   * VTEX fingerprint information.
   */
  vtexFingerprint: string;
  /**
   * Chargeback information.
   */
  chargeback: string;
  /**
   * White signature (anti-fraud list) information.
   */
  whiteSignature: string;
  /**
   * Responsible for transaction request.
   */
  owner: string;
  /**
   * Order identitication.
   */
  orderId: string;
  /**
   * HTTP client used in the transaction.
   */
  userAgent: string;
  /**
   * Type of content accepted in the transaction request header.
   */
  acceptHeader: string;
  /**
   * Anti-fraud transaction identification.
   */
  antifraudTid: string;
  /**
   * Anti-fraud response information.
   */
  antifraudResponse: string;
  /**
   * Anti-fraud reference information.
   */
  antifraudReference: string;
  /**
   * Anti-fraud affiliation identification.
   */
  antifraudAffiliationId: string;
  /**
   * Store where the transaction was initiated.
   */
  channel: string;
  /**
   * Sales channel information.
   */
  salesChannel: string;
  /**
   * [URN](https://en.wikipedia.org/wiki/Uniform_Resource_Name) information.
   */
  urn: string;
  /**
   * Custom field for a transaction that can be displayed on the customer's invoice.
   */
  softDescriptor: string;
  /**
   * Indicates whether the payment transaction should be recurring.
   */
  markedForRecurrence: boolean;
  /**
   * Buyer information.
   */
  buyer: {
    /**
     * Buyer first name.
     */
    firstName?: string;
    /**
     * Buyer last name.
     */
    lastName?: string;
    /**
     * Type of the document informed by the buyer.
     */
    documentType?: string;
    /**
     * Document informed by the buyer.
     */
    document?: string;
    /**
     * Buyer email address.
     */
    email?: string;
    /**
     * Buyer address.
     */
    address?: string;
    /**
     * Buyer phone number.
     */
    phone?: string;
  };
}
/**
 * Object containing the reference route of transaction interactions.
 */
export interface Interactions {
  /**
   * Transaction interaction reference route.
   */
  href: string;
}
/**
 * Object containing the reference route of transaction settlements.
 */
export interface Settlements {
  /**
   * Transaction settlement reference route.
   */
  href: string;
}
/**
 * Object containing the reference route of transaction payments.
 */
export interface Payments {
  /**
   * Transaction payment reference route.
   */
  href: string;
}
/**
 * Object containing the reference route of transaction refunds.
 */
export interface Refunds {
  /**
   * Transaction refund reference route.
   */
  href: string;
}
/**
 * Object containing the reference route of transaction cancellations.
 */
export interface Cancellations {
  /**
   * Transaction cancellation reference route.
   */
  href: string;
}
/**
 * Object containing the reference route of transaction capabilities.
 */
export interface Capabilities {
  /**
   * Transaction capabilities reference route.
   */
  href: string;
}
/**
 * Transaction parameters information.
 */
export interface Field {
  /**
   * Transaction parameter name.
   */
  name: string;
  /**
   * Transaction parameter value.
   */
  value: string;
}
/**
 * Fields information.
 */
export interface Fields {
  /**
   * Card holder name.
   */
  holderName: string;
  /**
   * Card number information.
   */
  cardNumber: string;
  /**
   * CVV code.
   */
  validationCode: string;
  /**
   * Due date information. The date format is `mm/yy`.
   */
  dueDate: string;
  /**
   * Card holder documentation.
   */
  document: string;
  /**
   * Account identification.
   */
  accountId: string;
  /**
   * Array containing customer address information.
   */
  address: {
    /**
     * Address type.
     */
    addressType?: string;
    /**
     * Name of the receiver.
     */
    receiverName?: string;
    /**
     * Postal code information.
     */
    postalCode?: string;
    /**
     * City of the address.
     */
    city?: string;
    /**
     * State of the address.
     */
    state?: string;
    /**
     * Country of the address. ISO three-letter code.
     */
    country?: string;
    /**
     * Street of the address.
     */
    street?: string;
    /**
     * Number of the address.
     */
    number?: number;
    /**
     * Neighborhood of the address.
     */
    neighborhood?: string;
    /**
     * Complement to the address.
     */
    complement?: string;
    /**
     * Reference that may help in the location of the address.
     */
    reference?: string;
    /**
     * Array containing two floats with geocoordinates, first longitude, then latitude.
     */
    geoCoordinates?: number[];
  }[];
  /**
   * Callback URL information.
   */
  callbackUrl: string;
}
/**
 * Transaction information.
 */
export interface Transaction {
  /**
   * Transaction identification.
   */
  id: string;
  /**
   * Merchant name.
   */
  merchantName: string;
}
/**
 * Fields information.
 */
export interface Fields3 {
  /**
   * Card holder name.
   */
  holderName: string;
  /**
   * Card number information.
   */
  cardNumber: string;
  /**
   * CVV code.
   */
  validationCode: string;
  /**
   * Due date information. The date format is `mm/yy`.
   */
  dueDate: string;
  /**
   * Card holder documentation.
   */
  document: string;
  /**
   * Account identification.
   */
  accountId: string;
  /**
   * Array containing customer address information.
   */
  address: string[];
  /**
   * Callback URL information.
   */
  callbackUrl: string;
}
/**
 * Payment details information.
 */
// deno-lint-ignore no-empty-interface
export interface PaymentDetailsResponse {}
/**
 *  Transaction response body information.
 */
export interface SettleResponse {
  /**
   * Settle request identification.
   */
  id: string;
  /**
   * Token identification.
   */
  token: string;
  /**
   * Status code.
   */
  status: number;
  /**
   * Status detail information.
   */
  statusDetail: string;
  /**
   * Settlement processing date.
   */
  processingDate: string;
  /**
   * Refunded value.
   */
  refundedValue: number;
  /**
   * Refund operation token.
   */
  refundedToken: string;
  /**
   * Custom message.
   */
  message: string;
  /**
   * Custom code.
   */
  code: string;
  /**
   * Refunded value by connector (provider).
   */
  connectorRefundedValue: number;
  /**
   * Cancelled value.
   */
  cancelledValue: number;
}
/**
 * Transaction details response body information.
 */
export interface TransactionDetailsResponse {
  /**
   * Transaction identification.
   */
  id: string;
  /**
   * Transaction identification (same value of the `id` field).
   */
  transactionId: string;
  /**
   * Field used for anti-fraud to identify the transaction.
   */
  referenceKey: string;
  interactions: Interactions;
  settlements: Settlements;
  payments: Payments;
  refunds: Refunds;
  cancellations: Cancellations;
  capabilities: Capabilities;
  /**
   * Field that represents the possible transaction timeout statuses. Possible statuses and meanings: `0` = NotStarted, `1` = CancellingOrFinishing, `2` = CancellingOrFinishingByTimeout, `3` = CancelledOrFinished and `4` = TriesExceeded.
   */
  timeoutStatus: 0 | 1 | 2 | 3 | 4;
  /**
   * Total refunded transaction amount.
   */
  totalRefunds: number;
  /**
   * Transaction status.
   */
  status: string;
  /**
   * Transaction value.
   */
  value: number;
  /**
   * Receiver [URI](https://en.wikipedia.org/wiki/Uniform_Resource_Identifier) information.
   */
  receiverUri: string;
  /**
   * Transaction start date.
   */
  startDate: string;
  /**
   * Transaction authorization token.
   */
  authorizationToken: string;
  /**
   * Transaction authorization date.
   */
  authorizationDate: string;
  /**
   * Transaction completion token.
   */
  commitmentToken: string;
  /**
   * Transaction completion date.
   */
  commitmentDate: string;
  /**
   * Transaction refund token.
   */
  refundingToken: string;
  /**
   * Transaction refund date.
   */
  refundingDate: string;
  /**
   * Transaction cancellation token.
   */
  cancelationToken: string;
  /**
   * Transaction cancellation date.
   */
  cancelationDate: string;
  /**
   * Field containing information and values of payment parameters.
   */
  fields: Fields1[];
  /**
   * Transaction origin.
   */
  shopperInteraction: string;
  /**
   * Ip address information.
   */
  ipAddress: string;
  /**
   * Session identification.
   */
  sessionId: string;
  /**
   * Random [UUID](https://en.wikipedia.org/wiki/Universally_unique_identifier) V4 generated when the Request Capture receives a session that does not contain the macID already set. This value is set to the cookie `VtexRCMacIdv7`. The cookie has 1 year of expiration.
   */
  macId: string;
  /**
   * VTEX fingerprint information.
   */
  vtexFingerprint: string;
  /**
   * Chargeback information.
   */
  chargeback: string;
  /**
   * White signature (anti-fraud list) information.
   */
  whiteSignature: string;
  /**
   * Responsible for transaction request.
   */
  owner: string;
  /**
   * Order identitication.
   */
  orderId: string;
  /**
   * HTTP client used in the transaction.
   */
  userAgent: string;
  /**
   * Type of content accepted in the transaction request header.
   */
  acceptHeader: string;
  /**
   * Anti-fraud transaction identification.
   */
  antifraudTid: string;
  /**
   * Anti-fraud response information.
   */
  antifraudResponse: string;
  /**
   * Anti-fraud reference information.
   */
  antifraudReference: string;
  /**
   * Anti-fraud affiliation identification.
   */
  antifraudAffiliationId: string;
  /**
   * Store where the transaction was initiated.
   */
  channel: string;
  /**
   * Sales channel information.
   */
  salesChannel: string;
  /**
   * [URN](https://en.wikipedia.org/wiki/Uniform_Resource_Name) information.
   */
  urn: string;
  /**
   * Custom field for a transaction that can be displayed on the customer's invoice.
   */
  softDescriptor: string;
  /**
   * Indicates whether the payment transaction should be recurring.
   */
  markedForRecurrence: boolean;
  /**
   * Buyer information.
   */
  buyer: {
    /**
     * Buyer first name.
     */
    firstName?: string;
    /**
     * Buyer last name.
     */
    lastName?: string;
    /**
     * Type of the document informed by the buyer.
     */
    documentType?: string;
    /**
     * Document informed by the buyer.
     */
    document?: string;
    /**
     * Buyer email address.
     */
    email?: string;
    /**
     * Buyer address.
     */
    address?: string;
    /**
     * Buyer phone number.
     */
    phone?: string;
  };
}
/**
 * Payment parameters information.
 */
export interface Fields1 {
  /**
   * Payment parameter name.
   */
  name: string;
  /**
   * Payment parameter value.
   */
  value: string;
}
/**
 * Transaction settlement details response body information.
 */
export interface TransactionSettlementDetails {
  /**
   * Array containing requests information.
   */
  requests: Request[];
  /**
   * Array containing actions information.
   */
  actions: Action[];
}
/**
 * Requests information.
 */
export interface Request {
  /**
   * Transaction identification. This is the same `transactionId` value sent in the request path.
   */
  id: string;
  /**
   * Transaction settlement date.
   */
  date: string;
  /**
   * Transaction settlement value.
   */
  value: number;
}
/**
 * Actions information.
 */
export interface Action {
  /**
   * Payment identification.
   */
  paymentId: string;
  payment: Payment1;
  /**
   * Transaction settlement date.
   */
  date: string;
  /**
   * Settlement action date.
   */
  type: string;
  /**
   * Transaction settlement value.
   */
  value: number;
  /**
   * Connector transaction response information. This object can return different fields according to the internal configuration of each connector (payment provider), for example, `Tid`, `ReturnCode`, `authId`, among others).
   */
  connectorResponse: string;
}
/**
 * Object containing the transaction settlement reference route.
 */
export interface Payment1 {
  /**
   * Transaction reference settlement route.
   */
  href: string;
}
/**
 * Settle transaction request body information.
 */
export interface SettlethetransactionRequest {
  /**
   * Value to be settled. The value must be described without using separation for decimals, e.g. to capture a value of 320.50, send 32050.
   */
  value: number;
}
/**
 * Refund transaction request body information.
 */
export interface RefundthetransactionRequest {
  /**
   * Purchase value. The value must be described without using separation for decimals, e.g. to capture a value of 320.50, send 32050.
   */
  value: number;
  /**
   * Freigth value, if applicable.
   */
  freight?: number;
  /**
   * Tax value, if applicable.
   */
  tax?: number;
  /**
   * This field is filled with the content of the cart of the transaction, which can be obtained using [Get Orders](https://developers.vtex.com/docs/api-reference/orders-api?endpoint=get-/api/oms/pvt/orders/-orderId-) or [Transaction Details](https://developers.vtex.com/docs/api-reference/payments-gateway-api?endpoint=get-/api/pvt/transactions/-transactionId-) endpoints. It should only be included for transactions with split payment.
   */
  minicart?: {};
}
/**
 * Cancel transaction request body information.
 */
export interface CancelthetransactionRequest {
  /**
   * Value of the purchase that will be cancelled.
   */
  value: number;
}
