// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$0 from "./actions/cart/addItem.ts";
import * as $$$$$$$$$1 from "./actions/cart/removeAllItem.ts";
import * as $$$$$$$$$2 from "./actions/cart/removeItem.ts";
import * as $$$$$$$$$3 from "./actions/coupon/add.ts";
import * as $$$$$$$$$4 from "./actions/coupon/delete.ts";
import * as $$$$$$$$$5 from "./actions/createReview.ts";
import * as $$$$$$$$$6 from "./actions/wishlist/addItem.ts";
import * as $$$$$$$$$7 from "./actions/wishlist/removeItem.ts";
import * as $$$0 from "./loaders/cart.ts";
import * as $$$1 from "./loaders/productListingPage.ts";
import * as $$$2 from "./loaders/proxy.ts";
import * as $$$3 from "./loaders/wishlist.ts";

const manifest = {
  "loaders": {
    "cazco/loaders/cart.ts": $$$0,
    "cazco/loaders/productListingPage.ts": $$$1,
    "cazco/loaders/proxy.ts": $$$2,
    "cazco/loaders/wishlist.ts": $$$3,
  },
  "actions": {
    "cazco/actions/cart/addItem.ts": $$$$$$$$$0,
    "cazco/actions/cart/removeAllItem.ts": $$$$$$$$$1,
    "cazco/actions/cart/removeItem.ts": $$$$$$$$$2,
    "cazco/actions/coupon/add.ts": $$$$$$$$$3,
    "cazco/actions/coupon/delete.ts": $$$$$$$$$4,
    "cazco/actions/createReview.ts": $$$$$$$$$5,
    "cazco/actions/wishlist/addItem.ts": $$$$$$$$$6,
    "cazco/actions/wishlist/removeItem.ts": $$$$$$$$$7,
  },
  "name": "cazco",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
